apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-master
  labels:
    app: ticket-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-master
  template:
    metadata:
      labels:
        app: ticket-master
    spec:
      containers:
        - name: web
          # NOTE: kustomization.yaml will rewrite "ticket-master:latest" to your Docker Hub image:tag
          image: ticket-master:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
